service: kicker

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: eu-west-2

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  check-domain-availability:
    handler: bin/check-domain-availability
    events:
      - schedule: cron(0 12 * * ? *)
