on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SNS_ARN: ${{ secrets.AWS_SNS_ARN }}
  AWS_SNS_REGION: ${{ secrets.AWS_SNS_REGION }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: make test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: make build
      - run: mkdir zip
      - run: zip zip/ping.zip bin/ping
      - run: zip zip/domainfree.zip bin/domainfree
      - run: pip install awscli
      - run: aws s3 sync zip s3://${{ secrets.AWS_S3_BUCKET }} --delete
