on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SNS_ARN: ${{ secrets.AWS_SNS_ARN }}
  AWS_SNS_REGION: ${{ secrets.AWS_SNS_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: make test
      - uses: actions/setup-node@v1
      - run: npm install -g serverless@~1.83.0
      - run: make deploy